name: build
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
env:
  GCLOUD_SERVICE_KEY: ${{secrets.GCLOUD_SERVICE_KEY}}
  IMAGE: hono-api
  GAR: europe-west2-docker.pkg.dev
  REPO_GAR: europe-west2-docker.pkg.dev/iproov-palms-poc/palms

jobs:
  build:
    runs-on: ubuntu-20.04
    outputs:
      tag: ${{ steps.output-tag.outputs.tag }}
    steps:
      - uses: actions/checkout@v3
      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{secrets.GCLOUD_SERVICE_KEY}}
      - uses: docker/login-action@v3
        with:
          registry: ${{env.GAR}}
          username: _json_key
          password: ${{env.GCLOUD_SERVICE_KEY}}
      - run: |
          BRANCH=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}} \
          VERSION=$(jq -r .version "./deno.json") \
          SHORT_SHA=$(git rev-parse --short HEAD) \
          && echo "TAG=${BRANCH/\//-}-$VERSION-$SHORT_SHA-$(date '+%Y%m%d-%H%M%S')" >> $GITHUB_ENV
      - uses: denoland/setup-deno@v1
      - run: docker build --build-arg="$TAG" -t ${{env.IMAGE}} .
      - run: docker tag ${{env.IMAGE}} ${{env.REPO_GAR}}/${{env.IMAGE}}:${{env.TAG}}
      - run: docker push ${{env.REPO_GAR}}/${{env.IMAGE}}:${{env.TAG}}
      - id: output-tag
        run: echo "tag=${{env.TAG}}" >> $GITHUB_OUTPUT
      - uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: hono-api
          image: ${{env.REPO_GAR}}/${{env.IMAGE}}:${{env.TAG}}
          region: europe-west2
          skip_default_labels: true
          env_vars: |
            IMAGE=${{env.REPO_GAR}}/${{env.IMAGE}}:${{env.TAG}}
            TAG=${{env.TAG}}
          secrets: |
            SECRET_A_VAR=SECRET_A:latest
            /secrets/SECRET_A_file=SECRET_A:latest
